# Generated by Django 5.1.4 on 2025-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_project_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjective',
            options={'verbose_name': 'Adjective', 'verbose_name_plural': 'Adjectives'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='adectives',
            new_name='adjectives',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='adectives',
            new_name='adjectives',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
